spring.application.name=MediKart
#spring.datasource.url=jdbc:mysql://localhost:3306/medikart?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=alohomora13
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.lazy-initialization=true

secreteJwtString= heybye13534heybye13534heybye13534heybye13534


cloudinary.cloud_name=dgdh9rrpv
cloudinary.api_key=814368927345756
cloudinary.api_secret=IPUWizy8SenYWOv8yFzFxs0Aakc