spring.application.name=MediKart
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
secreteJwtString= heybye13534heybye13534heybye13534heybye13534


cloudinary.cloud_name=dgdh9rrpv
cloudinary.api_key=814368927345756
cloudinary.api_secret=IPUWizy8SenYWOv8yFzFxs0Aakc